language: android
android:
  components:
    - tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

script:
  - ./gradlew -PtmdbApiKey=12345 build connectedCheck