language: android
android:
  components:
    - tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

script:
  - jdk_switcher use oraclejdk8
  - ./gradlew build connectedCheck